### ISSUE TITLE
Create and update yml files

### ISSUE THREAD

**Issue by roigcarlo** [simphony/simphony-metadata#1]
The following yml files need to be updated according to: https://publicwiki-01.fraunhofer.de/SimPhoNy-Project/index.php/SimPhoNy_Metadata_Schema
- Cuba.yml
- cuds_item.yml
- material_relation_definitions.yml

Simphony.yml needs to be split into 
- Physics Equations
- Material Relations
- Materials
- Boundaries
- Conditions

**Comment by tuopuu** [comment]
It seems that simphony.yml is not going to be that large and complex file that it really needs to be split into 5 separate files. 

I think that the main idea supporting splitting we had in the dev-team meeting was that SimPhoNy classes described in this file would be easier to update, and it would be easier to define new classes and place them in correct "categories" in these files. However, updating or adding new stuff is not going to happen so often. Once we roll out version 1.0, that should cover every Model/Engine we have in SimPhoNy at the moment. Also, version control will be straightforward when everything is in a single file. I think we should refrain from splitting simphony.yml for now, until there is a real need for it. @ahashibon, do you have some recommendation to this issue?

**Comment by ahashibon** [comment]
Agree!

**Comment by mehdisadeghi** [comment]
Having less files is definitely better for long term. In the beginning we can focus on two files, one for CUBA one for CUDS.

**Comment by kitchoi** [comment]
I agree with having less files.

**Comment by tuopuu** [comment]
cuba.yml was updated to the new yaml format. material_relations.yml was merged to simphony_metadata.yml in #7

**Comment by roigcarlo** [comment]
Implemented in #7
