### ISSUE TITLE
Add StateData definition to the metadata

### ISSUE THREAD

**Issue by mehdisadeghi** [simphony/simphony-metadata#13]
In order to create a standalone CUDS it is necessary to wrap multiple datasets inside a higher level container with certain information such as name and id. This would be helpful to have multiple StateData support in SimPhoNy, i.e. to have one StateData per time step.

**Comment by ahashibon** [comment]
This is a good idea. We should consider the scope of CUDS first. If a CUDS is made to support representing only one state of the system, then it itself is the container of all datasets (and all other pieces of the model puzzle). If however, we extend the scope of CUDS to allow managing and handling more than one state of the simulation (i.e., a sequence of states at consequent time steps or  solution steps). Then we need the State Data. 

In either case, introducing a state data now can be done independent of whether we choose to implement one state CUDS or one "Simulation", i.e., sequence CUDS. 

Will add a metadata description of state data then to the existing metadata in a new branch. It will be a simple access point of all data sets that belong to one state.

**Comment by ahashibon** [comment]
@mehdisadeghi  according to our discussions today and going back to the decision at the M24 meeting, a CUDS is supposed to describe a complete one state only. Therefore no additional explicit state data is needed. The state data is a conceptual element therefore. 

I will consider this issue closed, if someone has further comments please drop me a line.
