### ISSUE TITLE
SlipVelocity condition

### ISSUE THREAD

**Issue by khiltunen** [simphony/simphony-metadata#131]
SlipVelocity boundary condition does not need velocity as a parameter.

**Comment by ahashibon** [comment]
How it is supposed to be used?

**Comment by khiltunen** [comment]
Maybe it would be better to call it free slip velocity condition as it is stated in definition. Basically it is a condition where normal velocity is zero and tangential velocities are solved.

**Comment by stefanoborini** [comment]
Is this closed by the merged PR?

**Comment by ahashibon** [comment]
yes, can be closed.
