### ISSUE TITLE
Add basic CUBA to cuba.yml

### ISSUE THREAD

**Issue by ahashibon** [simphony/simphony-metadata#6]
A number of CUBA are assumed to be already defined in cuba.yml, but some are not yet defined defined there. Need to collect those and add them to cuba.yml.

**Comment by tuopuu** [comment]
This issue can be linked to #1, which I'm working on. We'll also need to remove some definition because of overlapping (for example CUBA.Material). I'll make a [WIP] PR so we can have discussion there.

**Comment by mehdisadeghi** [comment]
@ahashibon Could you please be more explicit and name the keys to add to the metadata?

**Comment by mehdisadeghi** [comment]
Fixed in #20, please one new issue for new keys if necessary.
