### ISSUE TITLE
keyword conflict arising from duplication of cuba.yml vs simphony_metadata.yml

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-metadata#64]
Our namespacing rules are all over the place, with the result that we now have two FACE entities, one in cuba.yml, the other in simphony_metadata.yml, both ending up in the keywords.py file, producing something that is invalid syntax.

**Comment by stefanoborini** [comment]
To address this, I think we should:

- Limit the CUBA namespace to derived types (the content of cuba.yml).
- Have a separate CUDS namespace where objects/relationships go. This means that 
    - the simphony_metadata.yml entries will end up in cuds.yml instead, where we will have a CUDS enum.
    - any reference that involves entities that are CUDS must have CUDS.CUDSNAME, instad of CUBA.CUDSNAME.
    - any reference to derived types that _are_ CUBA types will remain CUBA.CUBANAME.

**Comment by ahashibon** [comment]
The alternative, which had been discussed in previous issue, is to have one name space, all CUDS items and CUBA keys are CUDS items defined in one place. All referred to as CUBA.CUDS_ITEM (this will give the common universal attribute of a CUDS_ITEM).

**Comment by stefanoborini** [comment]
Closing. We only have one namespace: CUBA. We just need a smarter validator, and unify the file
