### ISSUE TITLE
INTEGRATION_TIME shoud have SOLVER_PARAMETER parent

### ISSUE THREAD

**Issue by ahashibon** [simphony/simphony-metadata#68]
Now we have 
`INTEGRATION_TIME:`
   `parent: CUBA.COMPUTATIONAL_METHOD`
which means integration time **is a** computational method! it should be  `SOLVER_PARAMETER` instead,

**Comment by ahashibon** [comment]
note: actual branch is called issue69! sorry, mistake with counting...

**Comment by stefanoborini** [comment]
Solved by #70
