### ISSUE TITLE
Meaning of variables in unclear and unspecified

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-metadata#82]
The ``variables`` entry is unclear in its use and purpose

307   LENNARD_JONES_6_12:
308     parent: CUBA.PAIR_POTENTIAL
309     definition: A Lennard-Jones 6-12 Potential
310     models: [CUBA.ATOMISTIC]
311     variables: [CUBA.POSITION, CUBA.POTENTIAL_ENERGY]
312     CUBA.CUTOFF_DISTANCE:
313       default: 1.0
314     CUBA.ENERGY_WELL_DEPTH:
315       default: 1.0
316     CUBA.VAN_DER_WAALS_RADIUS:
317       default: 1.0

**Comment by ahashibon** [comment]
These are meant to give more information and metadata on the equation. The variables correspond to the MODA template and aim at giving extra semantic knowledge on the equation defined and assist in giving meanning to them. Moreover, the collection of all variables in a CUDS indicate which variables should be expected and supported on the PARTICLES, MESH and LATTICE entities. Currently, they provide a way to query which variables are supprted by an equation (ME, PE, etc).

**Comment by stefanoborini** [comment]
@ahashibon Ok so briefly said it's the information needed somewhere else for the lennard jones entity to make sense. Correct?

**Comment by ahashibon** [comment]
yes! and this information should be carried/provided by each entity (here LJ) itself!

**Comment by stefanoborini** [comment]
Ok, I am getting conflicting information. Should be carried by the Lennard Jones object or should be carried somewhere else?

**Comment by ahashibon** [comment]
@stefano: The information itself is "stored" on the entity itself (in the VARIABLE entry), but will be utilised by wrappers or validators of CUDS! This is what I mean by "carried" the entity carry this information about itself as part of its own metadata.

**Comment by stefanoborini** [comment]
@ahashibon  How do you envision this concept to be converted into a python object?

**Comment by ahashibon** [comment]
now, for engine wrappers, simply that we can query this information on any entity hat has it. For visualisation wrappers for example would be able to use this information to prepare GUI, or to allocate space etc.

**Comment by stefanoborini** [comment]
I assume that with "this information" you mean the list, not the actual value of position and potential energy.
In other words, is the current object layout found in simphony/cuds/meta/lennard_jones_6_12.py what you would expect?

**Comment by ahashibon** [comment]
yes!

**Comment by stefanoborini** [comment]
The meaning has been extracted and rendered in the file specs. Closing.
