### ISSUE TITLE
Typo in INTEGRATION_STEP: defaut

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-metadata#85]
```
483   INTEGRATION_STEP:
484     parent: CUBA.COMPUTATIONAL_METHOD
485     definition: the current step, integration step, and final number of steps for a simulation stored on each cuds (a specific state).
486     CUBA.CURRENT:
487       default: 0
488     CUBA.SIZE:
489       defaut: 0
490     CUBA.FINAL:
491       defaut: 0 
```

**Comment by ahashibon** [comment]
@stefanoborini Thanks for catching this one!

**Comment by stefanoborini** [comment]
These mistakes have a large potential for creating incompatibilities. Not having a generator that does validation, and having to manipulate the file by hand makes it more likely that these things actually happen. I stress the importance for solving these issues as soon as possible, but this also requires that we establish and maintain these tools.

**Comment by ahashibon** [comment]
agree! we need the metaedit tool exactly to help on these issues!
